[package]
name = "day5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
rangemap = "1.4.0"
rayon = "1.8.0"

[[bin]]
name = "day5"
path = "main.rs"
